adding my junit4 assignment to feature branch
RahulKnolder/Junit_Assignment pull request #1
Opened 2023-04-08 09:54 UTC by RahulKnolder

review for junit4

2023-04-09 13:07 UTC, anup0060 requested changes

2023-04-09 13:07 UTC, anup0060 commented on src/test/java/juint_4/StringUtilsTest.java
> +    public void testIsPalindrome() {
split in different functions with each scenarios. 

ex - testIsPalindrome_givenExpectedInput 
     -testIsPalindrome_givenEmptyInput

2023-04-09 13:07 UTC, anup0060 commented on src/test/java/juint_4/StringUtilsTest.java
> +    public void testReverse() {
split in separate test functions

2023-04-11 10:20 UTC, RahulKnolder commented
I have tried to correct my mistake in junit4 assignment so please go through it

2023-04-12 17:53 UTC, anup0060 approved these changes

2023-04-12 17:53 UTC, merged