adding my junit 5 assignment to the repository
RahulKnolder/Junit_Assignment pull request #2
Opened 2023-04-08 12:05 UTC by RahulKnolder

please review my code

2023-04-09 13:10 UTC, anup0060 requested changes

2023-04-09 13:10 UTC, anup0060 commented on src/test/java/juint_5/PersonTest.java
> +    public void createInstance() {
method name should be setup

2023-04-09 13:10 UTC, anup0060 commented on src/test/java/juint_5/PersonTest.java
> +    public void testGetAge() throws InvalidAgeException {
split in separate test methods , don't club multiple scenarios.

2023-04-09 13:10 UTC, anup0060 commented on src/test/java/juint_5/PersonTest.java
> +    public void testSetAgeZero() throws InvalidAgeException {
test method names should be correct , see junit 4 review comments

2023-04-11 11:54 UTC, RahulKnolder commented
I have worked on the above reviews please go through it and let me know if I am still lacking in something

2023-04-12 17:52 UTC, anup0060 approved these changes

2023-04-12 17:52 UTC, merged